apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: frank-namespace
type: Opaque
stringData:
  JWT_SECRET: somethingsecret
  MONGODB_URI: mongodb+srv://Blackflame:Freegame@cluster0.xt9xxik.mongodb.net/amazona_db?retryWrites=true&w=majority
  PAYPAL_CLIENT_ID: ""
  CLOUDINARY_CLOUD_NAME: dr6yye7b1
  CLOUDINARY_API_KEY: "476664254519315"
  CLOUDINARY_URL: ""
  CLOUDINARY_API_SECRET: hN2w1IqMwXNsvU8sLYGGGI7Ry-M
  GOOGLE_API_KEY: ""
  MAILGUN_DOMIAN: ""
  MAILGUN_API_KEY: ""
  PASS: rstzslrpsmctqejs
  NODE_ENV: production
  HOST: smtp.gmail.com
  SERVICE: gmail
  EMAIL_PORT: "465"
  SECURE: "true"
  USER: engineerfranklyn@gmail.com
  DATABASE_USER: chiemelaumeh
  DATABASE_HOST: cosc-3380-team-project-db.cfqc4aaskdqc.us-east-1.rds.amazonaws.com
  DATABASE_PASSWORD: hDPD2bnKfSU9uayC1bKn
  DATABASE_DATABASE: cosc-3380-team-project-db