---
apiVersion: v1
kind: Namespace
metadata:
  name: shopping-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shopping-namespace
  name: shopping-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: real-shopping
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: real-shopping
    spec:
      containers:
      - image: 577638372446.dkr.ecr.us-east-1.amazonaws.com/shopping-app-rep:latest
        imagePullPolicy: Always
        name: real-shopping
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  namespace: shopping-namespace
  name: shopping-service
spec:
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: real-shopping
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: shopping-namespace
  name: shopping-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: shopping-service
              port:
                number: 80


