---
- name: Configure EC2 instances
  hosts: all
  become: true
  tasks:

    - name: Update and upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required software
      apt:
        name:
          - nginx
          - git
          - curl
        state: present

    - name: Create a new user
      user:
        name: deployuser
        shell: /bin/bash
        createhome: yes
        state: present

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        line: 'deployuser ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Set environment variables
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
      loop:
        - 'APP_ENV=production'
        - 'APP_DEBUG=false'
        - 'DATABASE_URL=mysql://user:password@localhost/dbname'

    - name: Restart Nginx (if installed)
      service:
        name: nginx
        state: restarted
        enabled: yes